### ISSUE TITLE
error in Fuseki environment

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lucene-zh#1]
here's another error:

```
[2018-05-16 20:48:23] ParserARQUpdate ERROR Unexpected throwable: 
java.lang.NullPointerException: input AttributeSource must not be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.apache.lucene.util.AttributeSource.<init>(AttributeSource.java:84)
	at org.apache.lucene.analysis.TokenStream.<init>(TokenStream.java:105)
	at org.apache.lucene.analysis.TokenFilter.<init>(TokenFilter.java:33)
	at io.bdrc.lucene.zh.PinyinNumberedToMarkedFilter.<init>(PinyinNumberedToMarkedFilter.java:64)
	at io.bdrc.lucene.zh.ChineseAnalyzer.createComponents(ChineseAnalyzer.java:285)
```

I'm not sure what triggers it...

**Comment by eroux** [comment]
I think it would be clearer if the exceptions in

https://github.com/BuddhistDigitalResourceCenter/lucene-zh/blob/master/src/main/java/io/bdrc/lucene/zh/ChineseAnalyzer.java

were killing the thing instead of trying to make it a non working zombie

**Comment by drupchen** [comment]
are you refering to the try / catch blocks such as [this one](https://github.com/BuddhistDigitalResourceCenter/lucene-zh/blob/master/src/main/java/io/bdrc/lucene/zh/ChineseAnalyzer.java#L233)? 

I guess it is not the errors I throw because the profile doesn't exist…

**Comment by eroux** [comment]
I'm referring to these indeed. In that case there should be a `return null;` I think after the `e.printStackTrace();`, otherwise errors should pile up until it's unclear where the first error was

**Comment by eroux** [comment]
looks good now
